WIP: Added option to configure IPv8 with raw private key material
Tribler/py-ipv8 pull request #1039
Opened 2021-08-19 11:08 UTC by qstokkink

Fixes #1037
Fixes #1038

This PR:

 - Adds the option to configure keys with raw private key material (in b64 format).
 - Updates the configuration documentation to have a section for the key format.
 - Removes ancient (and ugly!) key loading practices.

2021-08-19 11:08 UTC, qstokkink commented
validate

2021-08-19 11:17 UTC, qstokkink commented
Ready for review; remaining Flake8 and Pylint errors are due to the `ipv8_service.py` import method.

2021-09-13 08:44 UTC, devos50 commented
validate

2021-09-13 10:10 UTC, devos50 approved these changes

2021-09-13 10:10 UTC, devos50 commented on ipv8/configuration.py
> +            self.config['keys'] = [key for key in self.config['keys'] if key["alias"] != alias]
Minor inconsistency of using " or ' for accessing dict indices.

2021-09-13 10:12 UTC, devos50 requested changes
The `M2CryptoSK` can actually be removed I think 👍

2021-09-13 10:22 UTC, qstokkink commented
validate

2021-09-13 10:29 UTC, devos50 approved these changes

2021-09-13 10:29 UTC, merged