Updated Serializer to be more efficient
Tribler/py-ipv8 pull request #874
Opened 2020-09-30 12:39 UTC by egbertbouman

This PR:
* Updates `Serializer` to make it more efficient
* Updates `EZPackOverlay` so that there is less string slicing and fewer lists are being created
* Renames the (un)packing functions that take a `Serializable` as an argument
* Removes `pack(_multiple)`/`unpack(_multiple)` functions
* Removes `optional_format_list` as its use is limited, and it's hurting unpacking performance. I've intentionally put this in a separate commit, so it's easy to undo in case we decide to keep it.

With the updated serializer, the time spent (un)serializing typically decreases by 20+%.
For instance, for intro-request/responses the decrease varies between 21-38%. Currently:
```
Serializing 1,000,000 intro-request packets: 5.6937067 s
Serializing 1,000,000 intro-response packets: 7.4839985 s
Unserializing 1,000,000 intro-request packets: 7.712827699999998 s
Unserializing 1,000,000 intro-response packets: 9.7632044 s
```

With this PR:
```
Serializing 1,000,000 intro-request packets: 4.4311537 s
Serializing 1,000,000 intro-response packets: 5.894732000000001 s
Unserializing 1,000,000 intro-request packets: 4.850328299999999 s
Unserializing 1,000,000 intro-response packets: 6.008891500000001 s
```

2020-09-30 13:29 UTC, qstokkink commented
It seems we are experiencing technical difficulties: `Failure: 'pylint is not installed'`.

2020-09-30 13:37 UTC, egbertbouman commented
@qstokkink Nice catch! I didn't even notice, considering the check still passed.

2020-09-30 13:38 UTC, qstokkink commented
retest this please

2020-09-30 13:40 UTC, qstokkink commented
@egbertbouman I noticed a hanging parenthesis and I wondered why Pylint didn't catch it. Turns out, it wasn't running.

2020-09-30 13:41 UTC, qstokkink commented
retest this please

2020-09-30 13:44 UTC, qstokkink commented
retest this please

2020-09-30 13:57 UTC, qstokkink commented
retest this please

2020-09-30 14:12 UTC, qstokkink commented
retest this please

2020-09-30 14:26 UTC, qstokkink commented
retest this please

2020-09-30 14:28 UTC, qstokkink commented
retest this please

2020-09-30 14:32 UTC, qstokkink commented
retest this please

2020-09-30 14:39 UTC, qstokkink commented
retest this please

2020-09-30 14:40 UTC, qstokkink commented
retest this please

2020-09-30 15:10 UTC, qstokkink commented
Our sincere apologies for this technical intermission, please rebase onto the latest `master`.

2020-09-30 15:15 UTC, egbertbouman commented
@qstokkink Thanks, the pylint check is working now!

2020-09-30 16:00 UTC, qstokkink commented
As this is hyper-critical functionality, I'll perform an extended check beyond the PR test suite (running through the documentation, periodic network health scripts, etc.) when this PR is done. The final review will take a bit longer than usual.

2020-10-01 11:20 UTC, qstokkink commented
retest this please

2020-10-01 13:17 UTC, qstokkink requested changes
I have finished the first half of my review: please address these two minor points.

I will now move into the second half of this review and run this code through all of our documentation and scripts.

2020-10-01 13:17 UTC, qstokkink commented on ipv8/messaging/serialization.py
> +        :param serializable: the serializable classe to get the format from and unpack to
"classe" -> "class"

2020-10-01 13:26 UTC, egbertbouman commented on ipv8/REST/isolation_endpoint.py
> +            address_str = args['ip']
Done.

2020-10-01 13:27 UTC, egbertbouman commented on ipv8/messaging/serialization.py
> +        :param serializable: the serializable classe to get the format from and unpack to
Done.

2020-10-01 14:31 UTC, merged